uploads = []
generated = []

[[outputs]]
id = "uJFmELHkH1DTbD3RWUQJQ"
uri = "file://jobjugaad-ai.zip"
type = "unspecified"
title = "Job Jugaad AI — Complete Source (v3)"

[[outputs]]
id = "0sSvn3lKXh_vSUq906RFs"
uri = "file://jobjugaad-clean.zip"
type = "unspecified"
title = "Job Jugaad AI — Clean Source (v3)"
